services:
  - type: web
    name: ncino-arcades
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec ruby app.rb -o 0.0.0.0 -p $PORT
    envVars:
      - key: RACK_ENV
        value: production
